# Generated by Django 5.0.6 on 2024-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OriginalUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("originalUrl", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "originalUrl",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="urlshortnerapp.originalurl",
                    ),
                ),
            ],
        ),
    ]
